name: Branch Management

on:
  push:
    branches:
      - 'feature-002/add-integration-whatsapp'

jobs:
  merge-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Merge to Dev
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin Dev
          git checkout Dev
          
          if git merge-base --is-ancestor ${{ github.ref }} Dev; then
            echo "Branch is already merged into Dev"
          else
            if git merge ${{ github.ref }} --no-ff --allow-unrelated-histories -m "Merge ${{ github.ref }} into Dev"; then
              git push origin Dev
            else
              git merge --abort
              git checkout ${{ github.ref }}
              git checkout -b temp-merge-branch
              git checkout Dev
              git merge temp-merge-branch -X theirs --no-ff --allow-unrelated-histories -m "Merge ${{ github.ref }} into Dev (resolved conflicts)"
              git push origin Dev
            fi
          fi

  test:
    needs: merge-to-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Ejecutando pruebas..."
          # Por ejemplo: npm test

  merge-to-qa:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Merge to QA
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin QA
          git checkout QA
          git merge origin/Dev --no-ff --allow-unrelated-histories -m "Merge Dev into QA"
          git push origin QA